export const HOME = "/";
export const ACCOUNT = "/account";
export const SHOP ="/shop";
export const SHOP_DETAIL = "/shop/:slug"
export const BLOG = "/blog"
export const BLOG_SLUG ="/blog/:slug"
export const SHOPPING_CART ="/shopping-cart";
export const SHOPPING_CART_CHECKOUT = "/shopping-cart/check-out"
export const SHIPING_RETURN ="/shipping-and-return";
export const ORDER_COMPLETE ="/order-complete";
export const FAQ = "/faq";
export const CONTACT_US ="/contact-us";
export const CONTACT_US_SLUG ="/contact-us/:slug"
export const LOGIN_REGISTER="/login-and-register";
export const ABOUT_US ="/about-us"